services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fastapi_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "fastapi_crud"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/fastapi_crud"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  backend:  # Eksik olan network tanımlaması eklendi!
    driver: bridge
