name: Deploy to Staging

on:
  push:
    branches:
      - dev  # Staging ortamına sadece dev branch'ten deployment yapılsın

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/project
            git pull origin dev
            docker stack deploy -c docker-stack.yml fastapi_stack
            docker system prune -f  # Gereksiz dosyaları temizle
